name = "ScoreP"
uuid = "754d78bd-90ed-4ac3-9051-8d885452e256"
authors = ["Carsten Bauer <carsten.bauer@uni-paderborn.de>"]
version = "0.1.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
